server:
  port: 8090
spring:
  application:
    name: "applications-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    applications: "/api/v1/solicitudes"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "applications_db"
    schema: "public"
    username: "postgres"
    password: "postgres"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
    path-find-user-by-document-number: /api/v1/usuarios/{documentNumber}
    path-find-users-by-emails: /api/v1/usuarios/by-emails
jwt:
  keystore-location: /Users/wilderpacpachuaman/Documents/certificados/applications-keystore.jceks
  keystore-password: changeit
  key-alias: jwt-signer

resilience4j:
  circuitbreaker:
    instances:
      getUsersByEmails:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      getUserByDocumentNumber:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
